name: openpanel_analytics
description: A Flutter plugin for Openpanel Analytics. This uses the events API to send clickevents and goals to Openpanel Analytics.
version: 0.2.0
homepage: https://github.com/jfr/flutter_openpanel_analytics.git
issue_tracker: https://github.com/jfr/flutter_openpanel_analytics/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4
  fk_user_agent: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg